<div class="<?=getBGClass()?> <?=$name?>-container section-container">
    <div class="container <?=$name?>">
        <div class="row">
            <div class="col <?=$name?> section-description wow fadeIn">
                <div class="divider-1 wow fadeInUp" style="height: 45px"><span></span></div>
            </div>
        </div>
    </div>
</div>

<footer class="col bg-primary text-white">
    <p style="text-align: center">
        Erstellt von J&ouml;rn Schlingensiepen
    </p>
</footer>
<script src="assets/js/jquery-3.2.1.min.js"></script>
<script src="assets/js/jquery-migrate-3.0.0.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery.backstretch.min.js"></script>
<script src="assets/js/wow.min.js"></script>
<script src="assets/js/retina-1.1.0.min.js"></script>
<script src="assets/js/waypoints.min.js"></script>
<script src="assets/js/scripts.js"></script>
</body>
</html>
