<!-- Navigation -->

<nav class="navbar navbar-dark fixed-top navbar-expand-md navbar-no-bg">
    <div class="container">
        <div onclick="scroll_to_top()">

        <a class="navbar-brand" href="#intro">Start</a>
        <button id="intro"
                class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="#stream">Stream</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="#tldr">TL&shy;;&shy;DR</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link " href="#facts">An&shy;lei&shy;tung</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="#rules">Dis&shy;clai&shy;mer und Re&shy;geln</a>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="#impressum">Im&shy;pres&shy;sum &amp; Da&shy;ten&shy;schutz</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

