<div class="col">
    <p>
        Alle wichtigen Informationen findet Ihr in unserem Wiki: <br/>
        &nbsp;&nbsp;&nbsp;<a target="_blank" href="https://wiki.maglab.space/wiki/PixelCompetition">https://wiki.maglab.space/wiki/PixelCompetition</a>
    </p>
    <p>
        Wann welches Protokoll aktiv ist und die Workshops stattfinden, steht im Fahrplan: <br/>
        &nbsp;&nbsp;&nbsp;<a target="_blank" href="https://wiki.maglab.space/wiki/PixelCompetition#Fahrplan_zur_rc3">https://wiki.maglab.space/wiki/PixelCompetition#Fahrplan_zur_rc3</a>
    </p>
    <p>
        Unser Jitsi für die Workshops findet Ihr hier: <br/>
        &nbsp;&nbsp;&nbsp;<a target="_blank" href="https://meet.maglab.space/PixelCompetition-RC3">https://meet.maglab.space/PixelCompetition-RC3</a>
    </p>
    <p>
        Infos zu den einzelnen Competitions findet Ihr hier: <br/>
        &nbsp;&nbsp;&nbsp; <a target="_blank" href="https://wiki.maglab.space/wiki/PixelCompetition#Competitions">https://wiki.maglab.space/wiki/PixelCompetition#Competitions</a>
    </p>
</div>

