<div class="col-sm-6">
    <h3>Impressum</h3>
    <p>
        Diese Seite ist ein Angebot von Jörn Schlingensiepen
    </p>
    <p>
    Verantwortlich im Sinne des Presserechts und des Mediendienste-Staatsvertrages ist:
    </p>
    <p>
        Jörn Schlingensiepen <br />
        <a href="mailto://joern@schlingensiepen.com">joern@schlingensiepen.com</a>
    </p>
</div>
<div class="col-sm-6">
    <h3>Datenschutz</h3>
    <p>
        Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:<br />
        J&ouml;rn Schlingensiepen <br />
        <a href="mailto://joern@schlingensiepen.com">joern@schlingensiepen.com</a><br />
    </p>
    <p>
        Die Betrachtung dieses Web-Angebotes ist ohne Angabe von personenbezogenen Daten möglich.
        Der eingebundene YouTube-Stream erzeugt bei YouTube die Daten, zu deren Verarbeitung 
        Sie dort Ihr Einverständnis gegeben haben.
        Sofern Sie am Wettbewerb teilnehmen und Pixel auf den gemeinsamen Canvas malen, werden diese
        auf dieser Web-Site und im Stream angezeigt, d.h. Teile der Daten werden prinzipbedingt an Dritte
        weitergegeben. Mit der Teilnahme stimmen Sie diesem Vorgehen zu und geben Ihre Einwilligung zur
        Veröffentlichung dieser Daten/Pixel. Pixeln Sie einfach nichts, was andere nicht sehen sollen.
    </p>
    <p>
        Ihre Rechte, bei einer zuständigen Datenschutzbehörde Beschwerde zu führen, bleiben von dieser
        Bestimmung unberührt. Wir würden uns aber über eine vorherige Kontaktaufnahme freuen, so dass wir
        etwaige Mängel direkt abstellen könnten.
    </p>
</div>

