<div class="col">
<p>
Für die PixelCompetition gelten die üblichen Regeln des zivilisierten Umgangs miteinander. 
Für alle, die nicht so genau wissen, was damit gemeint sein könnte, hier eine kurze Aufzählung wichtiger Punkte:
</p>
<p>
<ol>
    <li>
        Der Wettbewerb findet ausschließlich auf dem Spielfeld statt. Es gibt keine Hacks, DOS, DDOS oder sonstige Angriffe auf 
        die Gegner, die Competition ist nur hier. (vulgo: es gilt – wie überall – die 
        <a href="https://www.ccc.de/de/hackerethik" target="_blank">Hackerethik: CCC|Hackerethik)</a>
    </li>
    <li>
        Das Einspeisen von Bildern, Texten oder Symbolen, die Gewalt verherrlichen oder zur Ausgrenzung von Menschen aufrufen, 
        sind verboten;
        vgl. <a href="https://www.ccc.de/de/updates/2005/unvereinbarkeitserklaerung" 
		        target="_blank">https://www.ccc.de/de/updates/2005/unvereinbarkeitserklaerung</a>
    </li>
    <li>
        Da sich die Competition auch an Jung-Haecksen und Jung-Hacker richtet, ist das Einspeisen von pornographischen Bildern verboten.
    </li>
    <li>
        Wir stellen die Competition als lustigen Zeitvertreib zur Verfügung und freuen uns über Anregungen für die Zukunft.
    </li>
</ol></p>
</div>