<div class="top-content bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 text">
                <div class="row">
                    <div class="col-4">
                        <img class="wow fadeInRightBig" src="assets/img/logobig.png" width="90%">
                    </div>
                    <div class="col-8">
                        <h1 class="wow fadeInLeftBig">Pixel-Competition</h1>
                        <div class="description wow fadeInLeftBig">
                            <p>
                                Ein interaktiver Programmierwettbewerb
                            </p>
                        </div>
                    </div>
                </div>
                <div class="top-big-link wow fadeInDownBig">
                    Dieser Wettbewerb ist ein soziales Experiment, alle Teilnehmer malen gleichzeitig Bilder auf einem
                    gemeinsamen Canvas. Dabei gibt es verschiedene Protokolle, über die ein Pixel gezeichnet werden
                    kann. Zu vorgegebenen Zeitpunkten wird jeweils ein neues Protokoll freigegeben, so dass die
                    Teilnehmer dann um die Wette eigene Clients erstellen können.
                    Während der RC3 bieten wir Einsteigerworkshops zum Schreiben von PixelCompetition-Clients in
                    verschiedenen Programmiersprachen in unserem Jitsi an.
                </div>
                <div class="top-big-link wow fadeInUp">
                    <a class="btn btn-primary scroll-link" href="#tldr">TL;DR</a>
                    <a class="btn btn-primary scroll-link" href="#facts">Anleitung</a>
                </div>
            </div>
        </div>
    </div>
</div>