<div class="col">
    <p>
        Den aktuellen Canvas kann man bei YouTube in diesem Stream sehen <a target="_blank" href="https://www.youtube.com/user/jschlingensiepen/live">https://www.youtube.com/user/jschlingensiepen/live</a>
    </p>
    <p>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=UCaWrQoYW76IPQ8B6KZkBGDA" frameborder="0" allowfullscreen></iframe>
    </p>
</div>

